INSERT INTO ESTUDIANTE (NOMBRE,APELLIDO,EDAD) VALUES ('Juan','Torres',20);
INSERT INTO ESTUDIANTE (NOMBRE,APELLIDO,EDAD) VALUES ('Maria','Gomez',27);
INSERT INTO ESTUDIANTE (NOMBRE,APELLIDO,EDAD) VALUES ('Eva','Gonzalez',21);
INSERT INTO ESTUDIANTE (NOMBRE,APELLIDO,EDAD) VALUES ('Carlos','Pedraza',30);
COMMIT;