INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('ASUS','AMD',16);
INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('HP','INTEL',32);
INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('APPLE','AMD',64);
COMMIT;