INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('HP','AMD',8);
INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('LENOVO','ADM',8);
INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('ASUS','AMD',32);
INSERT INTO LAPTOP (MARCA,CPU,MEMORIA_RAM) VALUES ('MSI','INTEL',16);
COMMIT;